name: "Kubectl Aws Authenticator with File output"
description: "Connects to kubernetes cluster using kubectl commands. Supports AWS EKS via aws-iam-authenticator and prints output to file."
branding:
  icon: 'anchor'
  color: 'blue'
inputs:
  args:
    description: "Arguments of kubectl"
    required: true
runs:
  using: "docker"
  image: "Dockerfile"
  args:
    - ${{ inputs.args }}
