name: "Kubectl Aws Authenticator with File output"
description: "Interacts with kubernetes clusters calling kubectl commands. Integrates support for AWS EKS via aws-iam-authenticator and prints output in a file."
branding:
  icon: 'anchor'
  color: 'blue'
inputs:
  args:
    description: "Arguments of kubectl"
    required: true
runs:
  using: "docker"
  image: "Dockerfile"
  args:
    - ${{ inputs.args }}
